### ISSUE TITLE
Not working - views being blocked 

### ISSUE THREAD

**Issue by socialmediaguy** [soumyadityac/youtube-viewer#8]
Hi,
First of all, thanks for the hard work on the code:)

I gave it a go but am getting the below error repeatedly and have nto managed ot get a single viewing yet. 

**[12:24:44 PM] - WARN     An attempt to view https://www.youtube.com/watch?v=xxxxxx with IP: xx.xx.xx.x was probably blocked.**

Mayb YT is blocking this and it won't work? Good work on the code again and good try though:)

**Comment by socialmediaguy** [comment]
ahh didn't work...

ytview_2  |  [12:28:38 PM] - WARN     Entire view action in a batch failed. Waiting for TOR to acquire a new set of IPs

**Comment by soumyadityac** [comment]
YouTube and Google in itself, continuously checks for suspicious activity from an IP address to any of its services. In an attempt to minimise these exploitations, it will ask such visitors to solve captcha challenges - which the bot deems as a blocked attempt, since it's current feature set doesn't include auto captcha solving.

If you keep the bot running, eventually with time, as it pools more and more IP addresses from TOR, your success rate should improve.
